version: '3.8'

services:
  crawl4ai:
    image: unclecode/crawl4ai:latest
    container_name: crawl4ai
    ports:
      - "11235:11235"
    shm_size: "1gb"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11235/"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - LOG_LEVEL=INFO
    networks:
      - crawl4ai_network

  mcp-server:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: crawl4ai-mcp-server
    ports:
      - "8765:8765"
    volumes:
      - ./data:/app/data
    environment:
      - CRAWL4AI_URL=http://crawl4ai:11235
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8765
    restart: unless-stopped
    depends_on:
      crawl4ai:
        condition: service_healthy
    networks:
      - crawl4ai_network

networks:
  crawl4ai_network:
    driver: bridge

volumes:
  mcp_data:
