services:
  knowledge-server:
    build:
      context: ../..
      dockerfile: deployments/server/Dockerfile.api
    image: knowledge-server:latest
    container_name: knowledge-server
    network_mode: "host"
    volumes:
      - ../../data:/app/data
    env_file:
      - .env
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - CRAWL4AI_URL=http://localhost:11235
      - KG_SERVICE_URL=http://localhost:8088
      - IS_SERVER=true
    restart: unless-stopped
