services:
  api-server:
    build:
      context: ../..
      dockerfile: deployments/server/Dockerfile.api
    container_name: crawl4ai-api-server
    ports:
      - "8080:8080"
    volumes:
      - ../../data:/app/data
    env_file:
      - .env
    environment:
      - CRAWL4AI_URL=http://crawl4ai:11235
    restart: unless-stopped
    networks:
      - crawler_default

networks:
  crawler_default:
    external: true
