services:
  mcp-client:
    build:
      context: ../..
      dockerfile: deployments/client/Dockerfile
    container_name: crawl4ai-mcp-client
    env_file:
      - .env
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - host
